### ISSUE TITLE
Logger\TradeHistory - PDOStatement::execute - Connection reset by peer

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#102]
```
Shutdown Enabled at: 2021-02-15 16:18:18
Exception: Exception
Code: 0
Message: Notice: PDOStatement::execute(): send of 348 bytes failed with errno=104 Connection reset by peer in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 239
Strace:
#0 [internal function]: Kobens\Core\ErrorHandler->handler(8, 'PDOStatement::e...', '/home/dfelton/g...', 239, Array)
#1 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#2 vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(307): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#3 vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(263): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#4 src/Command/Command/Logger/TradeHistory.php(215): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#5 src/Command/Command/Logger/TradeHistory.php(138): Kobens\Gemini\Command\Command\Logger\TradeHistory->logTrade(Object(stdClass))
#6 src/Command/Command/Logger/TradeHistory.php(89): Kobens\Gemini\Command\Command\Logger\TradeHistory->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput), 1613355732599)
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\Logger\TradeHistory->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\Logger\TradeHistory), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(382): Symfony\Component\Console\Application->run()
#12 {main}
```

**Comment by dfelton** [comment]
For now this can be considered resolved after 6992e32136e3be329dbafbca2247a8b2b4a1d47a.

While acknowledging that a reconnect effort to the database would be more ideal than a constant ping, that is an architectural design pattern change and will be a separate effort from this ticket.
