### ISSUE TITLE
Thottler -- PDOStatement::execute(): send of 41 bytes failed with errno=104 Connection reset by peer

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#131]
```
Shutdown Enabled at: 2021-02-27 08:23:04
Exception: Exception
Code: 0
Message: Notice: PDOStatement::execute(): send of 41 bytes failed with errno=104 Connection reset by peer in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 239
Strace:
#0 [internal function]: Kobens\Core\ErrorHandler->handler(8, 'PDOStatement::e...', '...', 239, Array)
#1 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#4 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#5 src/Api/Rest/PrivateEndpoints/Request.php(86): Kobens\Core\Http\Request\Throttler->throttle()
#6 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#7 src/Command/Command/TradeRepeater/Seller.php(137): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '2.081882', '0.56271', 'repeater_3423_s...')
#8 src/Command/Command/TradeRepeater/Seller.php(106): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_3423_s...')
#9 src/Command/Command/TradeRepeater/Seller.php(82): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(416): Symfony\Component\Console\Application->run()
#15 {main}

```

**Comment by dfelton** [comment]
Believe this to be an issue isolated to just the `TradeRepeater\Buyer` and `TradeRepeater\Seller` classes, and being caused by the database hanging up on us when there is too long of a timeframe between a sell or buy being placed.

```
Shutdown Enabled at: 2021-03-07 01:25:57
Exception: Exception
Code: 0
Message: Notice: PDOStatement::execute(): send of 41 bytes failed with errno=104 Connection reset by peer in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php on line 239
Strace:
#0 [internal function]: Kobens\Core\ErrorHandler->handler(8, 'PDOStatement::e...', '/home/dfelton/g...', 239, Array)
#1 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#4 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#5 src/Api/Rest/PrivateEndpoints/Request.php(87): Kobens\Core\Http\Request\Throttler->throttle()
#6 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#7 src/Command/Command/TradeRepeater/Seller.php(137): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '0.004324', '511.45', 'repeater_4922_s...')
#8 src/Command/Command/TradeRepeater/Seller.php(106): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_4922_s...')
#9 src/Command/Command/TradeRepeater/Seller.php(82): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(418): Symfony\Component\Console\Application->run()
#15 {main}
```

Implementing a ping to the throttler's connection will be a cheap fix. Would be better if we re-connect though.
