### ISSUE TITLE
BookKeeper - UnprocessedRequestException

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#145]
```
Code: 0
Class: Amp\Http\Client\Connection\UnprocessedRequestException
Message: The request was not processed and can be safely retried
Trace:
#0 [internal function]: Amp\Http\Client\Connection\DefaultConnectionFactory->Amp\Http\Client\Connection\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(102): Generator->throw(Object(Amp\Socket\ConnectException))
#2 vendor/amphp/amp/lib/Failure.php(29): Amp\Coroutine->Amp\{closure}(Object(Amp\Socket\ConnectException), NULL)
#3 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Failure->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(156): Amp\Coroutine->resolve(Object(Amp\Failure))
#5 vendor/amphp/amp/lib/Coroutine.php(124): Amp\Coroutine->fail(Object(Amp\Socket\ConnectException))
#6 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'ajuk')
#7 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#8 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#9 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#10 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#11 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'ajuk')
#12 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('ajuk')
#13 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('ajuk', Resource id #636173, NULL)
#14 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.99)
#15 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#16 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#18 src/Api/WebSocket/MarketData/BookKeeper.php(32): Amp\Loop::run(Object(Closure))
#19 src/Command/Command/Market/BookKeeper.php(74): Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->openBook()
#20 src/Command/Command/Market/BookKeeper.php(55): Kobens\Gemini\Command\Command\Market\BookKeeper->main(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\Market\BookKeeper->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\Market\BookKeeper), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 bin/gemini(418): Symfony\Component\Console\Application->run()
#26 {main}

Previous:
Code: 0
Class: Amp\Http\Client\SocketException
Message: Connection to 'api.gemini.com:443' failed
Trace:
#0 [internal function]: Amp\Http\Client\Connection\DefaultConnectionFactory->Amp\Http\Client\Connection\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(102): Generator->throw(Object(Amp\Socket\ConnectException))
#2 vendor/amphp/amp/lib/Failure.php(29): Amp\Coroutine->Amp\{closure}(Object(Amp\Socket\ConnectException), NULL)
#3 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Failure->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(156): Amp\Coroutine->resolve(Object(Amp\Failure))
#5 vendor/amphp/amp/lib/Coroutine.php(124): Amp\Coroutine->fail(Object(Amp\Socket\ConnectException))
#6 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'ajuk')
#7 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#8 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#9 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#10 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#11 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'ajuk')
#12 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('ajuk')
#13 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('ajuk', Resource id #636173, NULL)
#14 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.99)
#15 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#16 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#18 src/Api/WebSocket/MarketData/BookKeeper.php(32): Amp\Loop::run(Object(Closure))
#19 src/Command/Command/Market/BookKeeper.php(74): Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->openBook()
#20 src/Command/Command/Market/BookKeeper.php(55): Kobens\Gemini\Command\Command\Market\BookKeeper->main(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\Market\BookKeeper->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\Market\BookKeeper), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 bin/gemini(418): Symfony\Component\Console\Application->run()
#26 {main}

Previous:
Code: 111
Class: Amp\Socket\ConnectException
Message: Connection to tcp://api.gemini.com:443 refused
Trace:
#0 [internal function]: Amp\Socket\DnsConnector::Amp\Socket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(105): Generator->send('ajuk')
#2 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'ajuk')
#3 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#5 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#6 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#7 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'ajuk')
#8 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('ajuk')
#9 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('ajuk', Resource id #636173, NULL)
#10 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.99)
#11 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#12 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#13 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#14 src/Api/WebSocket/MarketData/BookKeeper.php(32): Amp\Loop::run(Object(Closure))
#15 src/Command/Command/Market/BookKeeper.php(74): Kobens\Gemini\Api\WebSocket\MarketData\BookKeeper->openBook()
#16 src/Command/Command/Market/BookKeeper.php(55): Kobens\Gemini\Command\Command\Market\BookKeeper->main(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\Market\BookKeeper->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\Market\BookKeeper), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 bin/gemini(418): Symfony\Component\Console\Application->run()
#22 {main}

```

**Comment by dfelton** [comment]
Also impacted the TradeRepeater's Websocket based FillMonitor:

```
Shutdown Enabled at: 2021-03-04 16:39:14
Exception: Amp\Http\Client\Connection\UnprocessedRequestException
Code: 0
Message: The request was not processed and can be safely retried
Strace:
#0 [internal function]: Amp\Http\Client\Connection\DefaultConnectionFactory->Amp\Http\Client\Connection\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(102): Generator->throw(Object(Amp\Socket\ConnectException))
#2 vendor/amphp/amp/lib/Failure.php(29): Amp\Coroutine->Amp\{closure}(Object(Amp\Socket\ConnectException), NULL)
#3 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Failure->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(156): Amp\Coroutine->resolve(Object(Amp\Failure))
#5 vendor/amphp/amp/lib/Coroutine.php(124): Amp\Coroutine->fail(Object(Amp\Socket\ConnectException))
#6 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'pq')
#7 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#8 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#9 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#10 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#11 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'pq')
#12 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('pq')
#13 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('pq', Resource id #635, NULL)
#14 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.991)
#15 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#16 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#18 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(91): Amp\Loop::run(Object(Closure))
#19 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 bin/gemini(418): Symfony\Component\Console\Application->run()
#24 {main}

Previous Exception:
Exception: Amp\Http\Client\SocketException
Code: 0
Message: Connection to 'api.gemini.com:443' failed
Strace:
#0 [internal function]: Amp\Http\Client\Connection\DefaultConnectionFactory->Amp\Http\Client\Connection\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(102): Generator->throw(Object(Amp\Socket\ConnectException))
#2 vendor/amphp/amp/lib/Failure.php(29): Amp\Coroutine->Amp\{closure}(Object(Amp\Socket\ConnectException), NULL)
#3 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Failure->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(156): Amp\Coroutine->resolve(Object(Amp\Failure))
#5 vendor/amphp/amp/lib/Coroutine.php(124): Amp\Coroutine->fail(Object(Amp\Socket\ConnectException))
#6 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'pq')
#7 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#8 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#9 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#10 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#11 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'pq')
#12 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('pq')
#13 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('pq', Resource id #635, NULL)
#14 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.991)
#15 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#16 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#17 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#18 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(91): Amp\Loop::run(Object(Closure))
#19 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 bin/gemini(418): Symfony\Component\Console\Application->run()
#24 {main}

Previous Exception:
Exception: Amp\Socket\ConnectException
Code: 111
Message: Connection to tcp://api.gemini.com:443 refused
Strace:
#0 [internal function]: Amp\Socket\DnsConnector::Amp\Socket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(105): Generator->send('pq')
#2 vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, 'pq')
#3 vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(125): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#5 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(Object(Amp\Internal\PrivatePromise))
#6 vendor/amphp/amp/lib/functions.php(242): Amp\Deferred->resolve(Object(Amp\Internal\PrivatePromise))
#7 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Promise\{closure}(NULL, 'pq')
#8 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('pq')
#9 vendor/amphp/amp/lib/Loop/NativeDriver.php(223): Amp\Deferred->resolve('pq', Resource id #635, NULL)
#10 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 4.991)
#11 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#12 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#13 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#14 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(91): Amp\Loop::run(Object(Closure))
#15 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 bin/gemini(418): Symfony\Component\Console\Application->run()
#20 {main}
```
