### ISSUE TITLE
504 Gateway Timeout causes Emergency Shutdown

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#15]
```
  ["time"]=> string(19) "2019-10-23 10:52:27"
  ["message"]=> string(92) "<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
"
  ["class"]=> string(48) "Kobens\Gemini\Exception\InvalidResponseException"
  ["trace"]=> string(2169) "
#0 src/Api/Rest/Request/Order/Placement/NewOrder.php(131): Kobens\Gemini\Api\Rest\Request->throwResponseException('<html><body><h1...', 504)
#1 src/Api/Rest/Request.php(76): Kobens\Gemini\Api\Rest\Request\Order\Placement\NewOrder->throwResponseException('<html><body><h1...', 504)
#2 src/Api/Rest/Request/Order/Placement/NewOrder/ForceMaker.php(60): Kobens\Gemini\Api\Rest\Request->getResponse()
#3 src/Command/Command/TradeRepeater/Buyer.php(115): Kobens\Gemini\Api\Rest\Request\Order\Placement\NewOrder\ForceMaker->getResponse()
#4 src/Command/Command/TradeRepeater/Buyer.php(92): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->forceMaker(Object(Kobens\Gemini\Api\Param\ClientOrderId), 'btcusd', '0.2', '7797.50')
#5 src/Command/Command/TradeRepeater/Buyer.php(66): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(932): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(274): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(150): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 bin/gemini(100): Symfony\Component\Console\Application->run()
#11 {main}"
```

**Comment by dfelton** [comment]
Lets resolve this by

- [ ] Adding a `Kobens\Core\Exception\Http\GatewayTimeoutException` class
- [ ] Modifying `Kobens\Gemini\Api\Rest\Request` to throw our new exception object
- [ ] Modfying `Kobens\Gemini\Command\Command\TradeRepeater\Buyer::mainLoop()` to catch this class
  - NO Reverting of state of record should occur. We don't know for certain what the may or may not have done with the request. We'll leave it up to our (future) implementation of a repairer class to handle resolving state of the record.
- [ ] We should modify the main lops of other repeater objects to do the same.
