### ISSUE TITLE
Concurrent Running Commands need to use their own session keys to avoid InvalidNonceException

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#16]
With a growing number of simultaneously running processes for the `trade-repeater:*` commands we're running into more issues with new requests using older nonce values.

```
object(stdClass)#1 (4) {
  ["time"]=>
  string(19) "2019-10-23 12:03:27"
  ["message"]=> string(139) "{"result":"error","reason":"InvalidNonce","message":"Nonce '157185020700965600' has not increased since your last call to the Gemini API."}"
  ["class"]=> string(48) "Kobens\Gemini\Exception\InvalidResponseException"
  ["trace"]=> string(2169) "
#0 src/Api/Rest/Request/Order/Placement/NewOrder.php(131): Kobens\Gemini\Api\Rest\Request->throwResponseException('{"result":"erro...', 400)
#1 src/Api/Rest/Request.php(76): Kobens\Gemini\Api\Rest\Request\Order\Placement\NewOrder->throwResponseException('{"result":"erro...', 400)
#2 src/Api/Rest/Request/Order/Placement/NewOrder/ForceMaker.php(60): Kobens\Gemini\Api\Rest\Request->getResponse()
#3 src/Command/Command/TradeRepeater/Buyer.php(115): Kobens\Gemini\Api\Rest\Request\Order\Placement\NewOrder\ForceMaker->getResponse()
#4 src/Command/Command/TradeRepeater/Buyer.php(92): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->forceMaker(Object(Kobens\Gemini\Api\Param\ClientOrderId), 'btcusd', '0.2', '8135.00')
#5 src/Command/Command/TradeRepeater/Buyer.php(66): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(932): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(274): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(150): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 bin/gemini(100): Symfony\Component\Console\Application->run()
#11 {main}
"
}
```

Gemini's API Docs on [Private API invocation](https://docs.gemini.com/rest-api/#private-api-invocation) state that a nonce is bound to the API key ("session") used for the request. In order to eliminate the possibility of two or more simultaneously running `trade-repeater:*` processes having a clash in their nonce used, lets implement the capability for each TradeRepeater command to utilize their own API key. Also instead of throwing an `InvalidResponseException` in `Kobens\Gemini\Api\Request` we should probably revise this to throw a new type of Exception `InvalidNonceException`.

Requirements:
- [x] `...\TradeRepeater\*`  utilize their own API key
- [x] `Kobens\Api\Rest\Request` utilizes a `InvalidNonceException` class in this event

**Comment by dfelton** [comment]
After running all commands with latest commit for several hours, I'm deeming this issue resolved.
