### ISSUE TITLE
SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#175]
```
Shutdown Enabled at: 2021-03-24 07:01:18
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#2 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('SELL_FILLED')
#3 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('SELL_FILLED')
#4 src/Command/Command/TradeRepeater/Archiver.php(99): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#5 src/Command/Command/TradeRepeater/Archiver.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Archiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 bin/gemini(442): Symfony\Component\Console\Application->run()
#11 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#3 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('SELL_FILLED')
#4 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('SELL_FILLED')
#5 src/Command/Command/TradeRepeater/Archiver.php(99): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#6 src/Command/Command/TradeRepeater/Archiver.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Archiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(442): Symfony\Component\Console\Application->run()
#12 {main}


Shutdown Enabled at: 2021-03-24 07:01:21
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#2 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 bin/gemini(442): Symfony\Component\Console\Application->run()
#7 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#3 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 bin/gemini(442): Symfony\Component\Console\Application->run()
#8 {main}

```

**Comment by dfelton** [comment]
Interestingly, this happened to both copies of the application which were running (mine and my brother's)

```
Shutdown Enabled at: 2021-03-24 07:01:18
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 /home/dfelton/gemini/vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#2 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('SELL_FILLED')
#3 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('SELL_FILLED')
#4 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Archiver.php(99): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#5 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Archiver.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/dfelton/gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/dfelton/gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/dfelton/gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Archiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/dfelton/gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/dfelton/gemini/bin/gemini(442): Symfony\Component\Console\Application->run()
#11 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 /home/dfelton/gemini/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /home/dfelton/gemini/vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#3 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('SELL_FILLED')
#4 /home/dfelton/gemini/src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('SELL_FILLED')
#5 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Archiver.php(99): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#6 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Archiver.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/dfelton/gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Archiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/dfelton/gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/dfelton/gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Archiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/dfelton/gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/dfelton/gemini/bin/gemini(442): Symfony\Component\Console\Application->run()
#12 {main}


Shutdown Enabled at: 2021-03-24 07:01:21
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#2 /home/dfelton/gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/dfelton/gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/dfelton/gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/dfelton/gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/dfelton/gemini/bin/gemini(442): Symfony\Component\Console\Application->run()
#7 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 /home/dfelton/gemini/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /home/dfelton/gemini/src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#3 /home/dfelton/gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/dfelton/gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/dfelton/gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/dfelton/gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/dfelton/gemini/bin/gemini(442): Symfony\Component\Console\Application->run()
#8 {main}


dfelton@kobens@~$ cat gemini-ryan/var/emergency_shutdown
Shutdown Enabled at: 2021-03-24 07:01:18
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#2 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('BUY_READY')
#3 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('BUY_READY')
#4 src/Command/Command/TradeRepeater/Buyer.php(108): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#5 src/Command/Command/TradeRepeater/Buyer.php(91): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 bin/gemini(442): Symfony\Component\Console\Application->run()
#11 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#3 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('BUY_READY')
#4 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('BUY_READY')
#5 src/Command/Command/TradeRepeater/Buyer.php(108): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#6 src/Command/Command/TradeRepeater/Buyer.php(91): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(442): Symfony\Component\Console\Application->run()
#12 {main}


Shutdown Enabled at: 2021-03-24 07:01:21
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#2 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 bin/gemini(442): Symfony\Component\Console\Application->run()
#7 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#3 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 bin/gemini(442): Symfony\Component\Console\Application->run()
#8 {main}

```
