### ISSUE TITLE
TradeRepeater\Buyer - Connection reset by peer

### ISSUE THREAD

**Issue by dfelton-chwy** [dfelton/kobens-gemini#198]
This issue impacts multiple areas. Also does not seem to be necessarily due to connections hanging around for a long time. I state this as it seems to more commonly occur when placing a surge of buy orders after having just recently added a bunch of records to the `trade_repeater` table. (but not at the start of it, during the middle of orders being placed, which proves the connection was used recently)

```
Shutdown Enabled at: 2021-04-12 14:07:33
Exception: Exception
Code: 0
Message: Notice: PDO::beginTransaction(): send of 22 bytes failed with errno=104 Connection reset by peer in vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php on line 306
Strace:
#0 [internal function]: Kobens\Core\ErrorHandler->handler(8, 'PDO::beginTrans...', '...', 306, Array)
#1 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php(306): PDO->beginTransaction()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(75): Zend\Db\Adapter\Driver\Pdo\Connection->beginTransaction()
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#4 src/Api/Rest/PublicEndpoints/Request.php(69): Kobens\Core\Http\Request\Throttler->throttle()
#5 src/Api/Rest/PublicEndpoints/Ticker.php(21): Kobens\Gemini\Api\Rest\PublicEndpoints\Request->getResponse('/v1/pubticker/s...')
#6 src/Api/Market/GetPrice.php(74): Kobens\Gemini\Api\Rest\PublicEndpoints\Ticker->getData('sandusd')
#7 src/Api/Market/GetPrice.php(56): Kobens\Gemini\Api\Market\GetPrice->getPriceViaTicker('sandusd')
#8 src/Api/Market/GetPrice.php(32): Kobens\Gemini\Api\Market\GetPrice->getData('sandusd')
#9 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(86): Kobens\Gemini\Api\Market\GetPrice->getAsk('sandusd')
#10 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(65): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->getNewPrice(Object(Kobens\Gemini\Exchange\Currency\Pair), '0.67745', 'buy')
#11 src/Command/Command/TradeRepeater/Buyer.php(147): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '1', '0.67745', 'repeater_7184_b...')
#12 src/Command/Command/TradeRepeater/Buyer.php(116): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_7184_b...')
#13 src/Command/Command/TradeRepeater/Buyer.php(91): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 bin/gemini(443): Symfony\Component\Console\Application->run()
#19 {main}
```

_Originally posted by @dfelton in https://github.com/dfelton/kobens-gemini/issues/176#issuecomment-817864055_

**Comment by dfelton-chwy** [comment]
This issue is caused by the public throttler's database connection dropping on us. We've tried to fix this in the past but only addressed the private throttler's connection (using a ping).
