### ISSUE TITLE
TradeRepeater\Buyer - InvalidQueryException

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#202]
```
Shutdown Enabled at: 2021-05-17 14:44:26
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#2 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('BUY_READY')
#3 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('BUY_READY')
#4 src/Command/Command/TradeRepeater/Buyer.php(124): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#5 src/Command/Command/TradeRepeater/Buyer.php(106): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 bin/gemini(444): Symfony\Component\Console\Application->run()
#11 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/TradeRepeater/Model/Resource/Trade.php(79): Zend\Db\Adapter\Adapter->query('SELECT id FROM ...', Array)
#3 src/TradeRepeater/Model/Resource/Trade.php(55): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatusIds('BUY_READY')
#4 src/TradeRepeater/Model/Resource/Trade/Action/AbstractAction.php(40): Kobens\Gemini\TradeRepeater\Model\Resource\Trade->getActiveByStatus('BUY_READY')
#5 src/Command/Command/TradeRepeater/Buyer.php(124): Kobens\Gemini\TradeRepeater\Model\Resource\Trade\Action\AbstractAction->getHealthyRecords()
#6 src/Command/Command/TradeRepeater/Buyer.php(106): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(444): Symfony\Component\Console\Application->run()
#12 {main}
```

**Comment by dfelton** [comment]
Believe this happened when updating mysql with `dnf update` command... Must have restarted the server.

MariaDB Logs:
```
2021-05-17 14:44:26 0 [Note] /usr/libexec/mysqld (initiated by: unknown): Normal shutdown
2021-05-17 14:44:26 0 [Note] Event Scheduler: Purging the queue. 0 events
2021-05-17 14:44:26 0 [Note] InnoDB: FTS optimize thread exiting.
2021-05-17 14:44:26 0 [Note] InnoDB: Starting shutdown...
2021-05-17 14:44:26 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2021-05-17 14:44:26 0 [Note] InnoDB: Instance 0, restricted to 2006 pages due to innodb_buf_pool_dump_pct=25
2021-05-17 14:44:26 0 [Note] InnoDB: Buffer pool(s) dump completed at 210517 14:44:26
2021-05-17 14:44:27 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-05-17 14:44:27 0 [Note] InnoDB: Shutdown completed; log sequence number 29491056123; transaction id 19945585
2021-05-17 14:44:27 0 [Note] /usr/libexec/mysqld: Shutdown complete
```
