### ISSUE TITLE
FillMonitor\WebSocket - InvalidQueryException

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#203]
```
Shutdown Enabled at: 2021-05-17 14:44:30
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(142): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(129): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->processMessage(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 [internal function]: Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\{closure}('a', NULL)
#3 vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('{"type":"heartb...')
#4 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '{"type":"heartb...')
#5 vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve('{"type":"heartb...')
#6 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#7 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(NULL)
#8 vendor/amphp/byte-stream/lib/IteratorStream.php(64): Amp\Deferred->resolve()
#9 vendor/amphp/amp/lib/Success.php(41): Amp\ByteStream\IteratorStream->Amp\ByteStream\{closure}(NULL, false)
#10 vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\Success->onResolve(Object(Closure))
#11 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(Object(Amp\Success))
#12 vendor/amphp/amp/lib/Internal/Producer.php(193): Amp\Deferred->resolve(Object(Amp\Success))
#13 vendor/amphp/amp/lib/Emitter.php(69): class@anonymous->complete()
#14 vendor/amphp/websocket/src/Rfc6455Client.php(357): Amp\Emitter->complete()
#15 vendor/amphp/websocket/src/Rfc6455Client.php(966): Amp\Websocket\Rfc6455Client->onData(1, '{"type":"heartb...', true)
#16 [internal function]: Amp\Websocket\Rfc6455Client->parser()
#17 vendor/amphp/websocket/src/Rfc6455Client.php(271): Generator->send('\x81~\x00\x85{"type":"he...')
#18 [internal function]: Amp\Websocket\Rfc6455Client->read()
#19 vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('\x81~\x00\x85{"type":"he...')
#20 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '\x81~\x00\x85{"type":"he...')
#21 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve('\x81~\x00\x85{"type":"he...')
#22 vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('\x81~\x00\x85{"type":"he...')
#23 vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('n', Resource id #486, NULL)
#24 vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.715)
#25 vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#26 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#27 vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#28 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(97): Amp\Loop::run(Object(Closure))
#29 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 bin/gemini(444): Symfony\Component\Console\Application->run()
#34 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(142): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(129): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->processMessage(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 [internal function]: Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\{closure}('a', NULL)
#4 vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('{"type":"heartb...')
#5 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '{"type":"heartb...')
#6 vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve('{"type":"heartb...')
#7 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#8 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(NULL)
#9 vendor/amphp/byte-stream/lib/IteratorStream.php(64): Amp\Deferred->resolve()
#10 vendor/amphp/amp/lib/Success.php(41): Amp\ByteStream\IteratorStream->Amp\ByteStream\{closure}(NULL, false)
#11 vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\Success->onResolve(Object(Closure))
#12 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(Object(Amp\Success))
#13 vendor/amphp/amp/lib/Internal/Producer.php(193): Amp\Deferred->resolve(Object(Amp\Success))
#14 vendor/amphp/amp/lib/Emitter.php(69): class@anonymous->complete()
#15 vendor/amphp/websocket/src/Rfc6455Client.php(357): Amp\Emitter->complete()
#16 vendor/amphp/websocket/src/Rfc6455Client.php(966): Amp\Websocket\Rfc6455Client->onData(1, '{"type":"heartb...', true)
#17 [internal function]: Amp\Websocket\Rfc6455Client->parser()
#18 vendor/amphp/websocket/src/Rfc6455Client.php(271): Generator->send('\x81~\x00\x85{"type":"he...')
#19 [internal function]: Amp\Websocket\Rfc6455Client->read()
#20 vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('\x81~\x00\x85{"type":"he...')
#21 vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '\x81~\x00\x85{"type":"he...')
#22 vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve('\x81~\x00\x85{"type":"he...')
#23 vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('\x81~\x00\x85{"type":"he...')
#24 vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('n', Resource id #486, NULL)
#25 vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.715)
#26 vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#27 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#28 vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#29 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(97): Amp\Loop::run(Object(Closure))
#30 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 bin/gemini(444): Symfony\Component\Console\Application->run()
#35 {main}
```

**Comment by dfelton** [comment]
Believe this happened when updating mysql with `dnf update` command... Must have restarted the server.

MariaDB Logs:
```
2021-05-17 14:44:26 0 [Note] /usr/libexec/mysqld (initiated by: unknown): Normal shutdown
2021-05-17 14:44:26 0 [Note] Event Scheduler: Purging the queue. 0 events
2021-05-17 14:44:26 0 [Note] InnoDB: FTS optimize thread exiting.
2021-05-17 14:44:26 0 [Note] InnoDB: Starting shutdown...
2021-05-17 14:44:26 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2021-05-17 14:44:26 0 [Note] InnoDB: Instance 0, restricted to 2006 pages due to innodb_buf_pool_dump_pct=25
2021-05-17 14:44:26 0 [Note] InnoDB: Buffer pool(s) dump completed at 210517 14:44:26
2021-05-17 14:44:27 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-05-17 14:44:27 0 [Note] InnoDB: Shutdown completed; log sequence number 29491056123; transaction id 19945585
2021-05-17 14:44:27 0 [Note] /usr/libexec/mysqld: Shutdown complete
```

**Comment by dfelton** [comment]
Related:
- #204 
- #202
