### ISSUE TITLE
Stats\DailyProfit - InvalidQueryException

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#204]
```
Shutdown Enabled at: 2021-05-17 14:44:31
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (70100 - 1927 - Connection was killed)
Strace:
#0 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#2 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 bin/gemini(444): Symfony\Component\Console\Application->run()
#7 {main}

Previous Exception:
Exception: PDOException
Code: 70100
Message: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(244): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 src/Command/Command/TradeRepeater/Stats/DailyProfit.php(85): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->getDayForUpdate()
#3 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Stats\DailyProfit), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 bin/gemini(444): Symfony\Component\Console\Application->run()
#8 {main}
```

**Comment by dfelton** [comment]
Believe this happened when updating mysql with `dnf update` command... Must have restarted the server.

MariaDB Logs:
```
2021-05-17 14:44:26 0 [Note] /usr/libexec/mysqld (initiated by: unknown): Normal shutdown
2021-05-17 14:44:26 0 [Note] Event Scheduler: Purging the queue. 0 events
2021-05-17 14:44:26 0 [Note] InnoDB: FTS optimize thread exiting.
2021-05-17 14:44:26 0 [Note] InnoDB: Starting shutdown...
2021-05-17 14:44:26 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2021-05-17 14:44:26 0 [Note] InnoDB: Instance 0, restricted to 2006 pages due to innodb_buf_pool_dump_pct=25
2021-05-17 14:44:26 0 [Note] InnoDB: Buffer pool(s) dump completed at 210517 14:44:26
2021-05-17 14:44:27 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-05-17 14:44:27 0 [Note] InnoDB: Shutdown completed; log sequence number 29491056123; transaction id 19945585
2021-05-17 14:44:27 0 [Note] /usr/libexec/mysqld: Shutdown complete
```

**Comment by dfelton** [comment]
Related:
- #203 
- #202
