### ISSUE TITLE
TradeRepeater\Seller - Notice: Undefined Property

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#208]
```
Shutdown Enabled at: 2021-05-19 14:25:03
Exception: Exception
Code: 0
Message: Notice: Undefined property: Kobens\Gemini\Exception\Api\Reason\MaintenanceException::$getMessage in src/Command/Command/TradeRepeater/Seller.php on line 157
Strace:
#0 src/Command/Command/TradeRepeater/Seller.php(157): Kobens\Core\ErrorHandler->handler(8, 'Undefined prope...', '/home/dfelton/g...', 157, Array)
#1 src/Command/Command/TradeRepeater/Seller.php(115): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_4220_s...')
#2 src/Command/Command/TradeRepeater/Seller.php(90): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 bin/gemini(444): Symfony\Component\Console\Application->run()
#8 {main}
```

**Comment by dfelton** [comment]
duplicate of #214
