### ISSUE TITLE
TradeRepeater\Watcher Command does not restart after DNS lookup failure

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#32]
After closing laptop lid and re-opening came back to find the script had aborted (probably due to network features turning off on laptop during lid closure).

Exact problem however, is on a DNS lookup for the host, if curl fails the command aborts itself. Stack trace below:

```
Code: 6
Class: Exception
Message: Curl Error
Stack Trace:
#0 src/Api/Rest/AbstractRequest.php(46): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PrivateEndpoints/FundManagement/GetNotionalBalances.php(20): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/TradeRepeater/Watcher/Helper/Data.php(86): Kobens\Gemini\Api\Rest\PrivateEndpoints\FundManagement\GetNotionalBalances->getBalances()
#3 src/TradeRepeater/Watcher/AccountNotionalBalance.php(19): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getNotionalBalances()
#4 src/Command/Command/TradeRepeater/Watcher.php(127): Kobens\Gemini\TradeRepeater\Watcher\AccountNotionalBalance::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), Object(Kobens\Core\Config))
#5 src/Command/Command/TradeRepeater/Watcher.php(94): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#6 src/Command/Command/TradeRepeater/Watcher.php(71): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(283): Symfony\Component\Console\Application->run()
#12 {main}

Previous:
Code: 0
Class: Exception
Message: {"body":"","response_code":0,"curl_errno":6,"curl_error":"Could not resolve: api.gemini.com (Could not contact DNS servers)","curlinfo_connect_time":0,"curlinfo_total_time":0.000542}
Stack Trace:
#0 src/Api/Rest/AbstractRequest.php(46): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PrivateEndpoints/FundManagement/GetNotionalBalances.php(20): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/TradeRepeater/Watcher/Helper/Data.php(86): Kobens\Gemini\Api\Rest\PrivateEndpoints\FundManagement\GetNotionalBalances->getBalances()
#3 src/TradeRepeater/Watcher/AccountNotionalBalance.php(19): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getNotionalBalances()
#4 src/Command/Command/TradeRepeater/Watcher.php(127): Kobens\Gemini\TradeRepeater\Watcher\AccountNotionalBalance::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), Object(Kobens\Core\Config))
#5 src/Command/Command/TradeRepeater/Watcher.php(94): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#6 src/Command/Command/TradeRepeater/Watcher.php(71): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(283): Symfony\Component\Console\Application->run()
#12 {main}
```

**Comment by dfelton** [comment]
With the retry logic on retry-safe endpoints, introduced in https://github.com/dfelton/kobens-gemini/pull/44, this particular issue for the TradeRepeater's Watcher command, can be considered resolved.

Sustained network outages would still cause the command to exit. For now this is OK.
