### ISSUE TITLE
OpenSSL SSL_connect: Connection reset by peer in connection to api.gemini.com:443

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#37]
```
Code: 35
Class: Exception
Message: Curl Error
Strace:
#0 src/Api/Rest/AbstractRequest.php(40): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PublicEndpoints/Ticker.php(16): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/Api/Market/GetPrice.php(74): Kobens\Gemini\Api\Rest\PublicEndpoints\Ticker->getData('btcusd')
#3 src/Api/Market/GetPrice.php(56): Kobens\Gemini\Api\Market\GetPrice->getPriceViaTicker('btcusd')
#4 src/Api/Market/GetPrice.php(42): Kobens\Gemini\Api\Market\GetPrice->getData('btcusd')
#5 src/TradeRepeater/Watcher/Helper/Data.php(55): Kobens\Gemini\Api\Market\GetPrice->getResult('btcusd')
#6 src/TradeRepeater/Watcher/TradeSpread.php(50): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getPriceResult('btcusd')
#7 src/Command/Command/TradeRepeater/Watcher.php(122): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#8 src/Command/Command/TradeRepeater/Watcher.php(88): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#9 src/Command/Command/TradeRepeater/Watcher.php(65): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(283): Symfony\Component\Console\Application->run()
#15 {main}

Previous:
Code: 0
Class: Exception
Message: {"body":"","response_code":0,"curl_errno":35,"curl_error":"OpenSSL SSL_connect: Connection reset by peer in connection to api.gemini.com:443 ","curlinfo_connect_time":1.36914,"curlinfo_total_time":1.453496}
Strace:
#0 src/Api/Rest/AbstractRequest.php(40): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PublicEndpoints/Ticker.php(16): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/Api/Market/GetPrice.php(74): Kobens\Gemini\Api\Rest\PublicEndpoints\Ticker->getData('btcusd')
#3 src/Api/Market/GetPrice.php(56): Kobens\Gemini\Api\Market\GetPrice->getPriceViaTicker('btcusd')
#4 src/Api/Market/GetPrice.php(42): Kobens\Gemini\Api\Market\GetPrice->getData('btcusd')
#5 src/TradeRepeater/Watcher/Helper/Data.php(55): Kobens\Gemini\Api\Market\GetPrice->getResult('btcusd')
#6 src/TradeRepeater/Watcher/TradeSpread.php(50): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getPriceResult('btcusd')
#7 src/Command/Command/TradeRepeater/Watcher.php(122): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#8 src/Command/Command/TradeRepeater/Watcher.php(88): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#9 src/Command/Command/TradeRepeater/Watcher.php(65): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(283): Symfony\Component\Console\Application->run()
```

**Comment by dfelton** [comment]
At first glance I'd say this could be handled by the Ticker to retry some for additional fault tolerance.

Unfortunately given the nature of this app, I'm thinking handling curl errors the same for all API endpoints won't be appropriate. For example if we were to get disconnected while having partially received a response it's fine to replay the request for was are essentially GET calls, but not calls which may POST a new order or status change on an existing order.

**Comment by dfelton** [comment]
With the logic changes from https://github.com/dfelton/kobens-gemini/pull/44, that retry certain endpoints that are retry-safe. This is now a non-issue for now. 

Sustained network outages would cause the command to exit but for now this is OK.
