### ISSUE TITLE
Can Get Order Status support "client_order_id"?

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#45]
While not documented in their API docs it appears based off this error message from the exchange that we can get order status from client_order_id.

This ability would prove quite useful especially for certain scenarios with our Trade Repeater.

```
Shutdown Enabled at: 2020-05-11 10:06:48
Exception: Kobens\Gemini\Exception
Code: 400
Message: Must supply either order_id or client_order_id, not both!
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(113): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(24): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(151): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(580279065)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(100): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(580279065)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(64): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(334): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"body":"{\"result\":\"error\",\"reason\":\"ConflictingOptions\",\"message\":\"Must supply either order_id or client_order_id, not both!\"}","response_code":400}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(113): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(24): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(151): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(580279065)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(100): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(580279065)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(64): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(334): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by dfelton** [comment]
Turns out we can. Feature added in https://github.com/dfelton/kobens-gemini/pull/44

Will make further use of this down the road.
