### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#46]
```
Code: 56
Class: Exception
Message: Curl Error
Strace:
#0 src/Api/Rest/AbstractRequest.php(40): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/GetActiveOrders.php(15): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/TradeRepeater/Watcher/Helper/Data.php(66): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\GetActiveOrders->getOrders()
#3 src/TradeRepeater/Watcher/TradeSpread.php(21): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getOrdersData()
#4 src/Command/Command/TradeRepeater/Watcher.php(122): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#5 src/Command/Command/TradeRepeater/Watcher.php(88): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#6 src/Command/Command/TradeRepeater/Watcher.php(65): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(283): Symfony\Component\Console\Application->run()
#12 {main}

Previous:
Code: 0
Class: Exception
Message: {"body":"","response_code":0,"curl_errno":56,"curl_error":"OpenSSL SSL_read: Connection reset by peer, errno 54","curlinfo_connect_time":0.078285,"curlinfo_total_time":1.671384}
Strace:
#0 src/Api/Rest/AbstractRequest.php(40): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/GetActiveOrders.php(15): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#2 src/TradeRepeater/Watcher/Helper/Data.php(66): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\GetActiveOrders->getOrders()
#3 src/TradeRepeater/Watcher/TradeSpread.php(21): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getOrdersData()
#4 src/Command/Command/TradeRepeater/Watcher.php(122): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#5 src/Command/Command/TradeRepeater/Watcher.php(88): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#6 src/Command/Command/TradeRepeater/Watcher.php(65): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(283): Symfony\Component\Console\Application->run()
```

Note: On latest version of master this will have yielded a different stack trace due to `CurlInterface` of `kobens-core`.

**Comment by dfelton** [comment]
With the retry logic on retry-safe endpoints, introduced by PR https://github.com/dfelton/kobens-gemini/pull/44, this is now a non-issue.

In the event of sustained network failure the command would still exit itself but for now this is OK.
