### ISSUE TITLE
MySQL Server Has Gone Away

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#47]
```
Code: 0
Class: Zend\Db\Adapter\Exception\InvalidQueryException
Message: Statement could not be executed (HY000 - 2006 - MySQL server has gone away)
Strace:
#0 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#3 src/Api/Rest/PublicEndpoints/Request.php(69): Kobens\Core\Http\Request\Throttler->throttle()
#4 src/Api/Rest/PublicEndpoints/Ticker.php(21): Kobens\Gemini\Api\Rest\PublicEndpoints\Request->getResponse('/v1/pubticker/b...')
#5 src/Api/Market/GetPrice.php(74): Kobens\Gemini\Api\Rest\PublicEndpoints\Ticker->getData('btcusd')
#6 src/Api/Market/GetPrice.php(56): Kobens\Gemini\Api\Market\GetPrice->getPriceViaTicker('btcusd')
#7 src/Api/Market/GetPrice.php(42): Kobens\Gemini\Api\Market\GetPrice->getData('btcusd')
#8 src/TradeRepeater/Watcher/Helper/Data.php(55): Kobens\Gemini\Api\Market\GetPrice->getResult('btcusd')
#9 src/TradeRepeater/Watcher/TradeSpread.php(50): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getPriceResult('btcusd')
#10 src/Command/Command/TradeRepeater/Watcher.php(132): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#11 src/Command/Command/TradeRepeater/Watcher.php(98): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#12 src/Command/Command/TradeRepeater/Watcher.php(73): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#13 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 bin/gemini(334): Symfony\Component\Console\Application->run()
#18 {main}

Previous:
Code: HY000
Class: PDOException
Message: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#4 src/Api/Rest/PublicEndpoints/Request.php(69): Kobens\Core\Http\Request\Throttler->throttle()
#5 src/Api/Rest/PublicEndpoints/Ticker.php(21): Kobens\Gemini\Api\Rest\PublicEndpoints\Request->getResponse('/v1/pubticker/b...')
#6 src/Api/Market/GetPrice.php(74): Kobens\Gemini\Api\Rest\PublicEndpoints\Ticker->getData('btcusd')
#7 src/Api/Market/GetPrice.php(56): Kobens\Gemini\Api\Market\GetPrice->getPriceViaTicker('btcusd')
#8 src/Api/Market/GetPrice.php(42): Kobens\Gemini\Api\Market\GetPrice->getData('btcusd')
#9 src/TradeRepeater/Watcher/Helper/Data.php(55): Kobens\Gemini\Api\Market\GetPrice->getResult('btcusd')
#10 src/TradeRepeater/Watcher/TradeSpread.php(50): Kobens\Gemini\TradeRepeater\Watcher\Helper\Data->getPriceResult('btcusd')
#11 src/Command/Command/TradeRepeater/Watcher.php(132): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'btcusd')
#12 src/Command/Command/TradeRepeater/Watcher.php(98): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#13 src/Command/Command/TradeRepeater/Watcher.php(73): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Output\ConsoleOutput), 'btcusd')
#14 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 vendor/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 bin/gemini(334): Symfony\Component\Console\Application->run()
#19 {main}
```

**Comment by dfelton** [comment]
Manual workaround available: bump up the [wait_timeout](https://mariadb.com/docs/reference/es/system-variables/wait_timeout/)

Related Issues: #36 #31

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-21 02:46:28
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (HY000 - 2006 - MySQL server has gone away)
Strace:
#0 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#3 src/Api/Rest/PrivateEndpoints/Request.php(86): Kobens\Core\Http\Request\Throttler->throttle()
#4 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#5 src/Command/Command/TradeRepeater/Seller.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '0.00197', '99.23', 'repeater_547_se...')
#6 src/Command/Command/TradeRepeater/Seller.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_547_se...')
#7 src/Command/Command/TradeRepeater/Seller.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 bin/gemini(346): Symfony\Component\Console\Application->run()
#13 {main}

Previous Exception:
Exception: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#4 src/Api/Rest/PrivateEndpoints/Request.php(86): Kobens\Core\Http\Request\Throttler->throttle()
#5 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#6 src/Command/Command/TradeRepeater/Seller.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '0.00197', '99.23', 'repeater_547_se...')
#7 src/Command/Command/TradeRepeater/Seller.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_547_se...')
#8 src/Command/Command/TradeRepeater/Seller.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 bin/gemini(346): Symfony\Component\Console\Application->run()
#14 {main}
```

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-02-03 09:18:48
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (HY000 - 2006 - MySQL server has gone away)
Strace:
#0 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#2 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#3 gemini/src/Api/Rest/PrivateEndpoints/Request.php(86): Kobens\Core\Http\Request\Throttler->throttle()
#4 gemini/src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#5 gemini/src/Command/Command/TradeRepeater/Seller.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '1.637738', '0.357', 'repeater_2007_s...')
#6 gemini/src/Command/Command/TradeRepeater/Seller.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_2007_s...')
#7 gemini/src/Command/Command/TradeRepeater/Seller.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 gemini/bin/gemini(359): Symfony\Component\Console\Application->run()
#13 {main}

Previous Exception:
Exception: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Strace:
#0 gemini/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(89): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler/Adapter/MariaDb.php(57): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->isInTransaction()
#3 gemini/vendor/kobens/kobens-core/src/Http/Request/Throttler.php(35): Kobens\Core\Http\Request\Throttler\Adapter\MariaDb->get('api.gemini.com:...')
#4 gemini/src/Api/Rest/PrivateEndpoints/Request.php(86): Kobens\Core\Http\Request\Throttler->throttle()
#5 gemini/src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#6 gemini/src/Command/Command/TradeRepeater/Seller.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '1.637738', '0.357', 'repeater_2007_s...')
#7 gemini/src/Command/Command/TradeRepeater/Seller.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_2007_s...')
#8 gemini/src/Command/Command/TradeRepeater/Seller.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 gemini/vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 gemini/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 gemini/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 gemini/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 gemini/bin/gemini(359): Symfony\Component\Console\Application->run()
#14 {main}
```

**Comment by jsfgreen** [comment]
Stop using zend.

**Comment by dfelton** [comment]
@jsfgreen 
![image](https://user-images.githubusercontent.com/2659558/107582558-48d86980-6bbf-11eb-8b7d-3b296ed3b21a.png)
