### ISSUE TITLE
Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus - Handle 502 Bad Gateway 

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#66]
Killed the trade-repeater this afternoon. A simple retry should be allowed here:

```
Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(???)
```

```
Shutdown Enabled at: 2021-01-09 13:23:19
Exception: Kobens\Gemini\Exception\InvalidResponseException
Code: 502
Message: <html>^M
<head><title>502 Bad Gateway</title></head>^M
<body>^M
<center><h1>502 Bad Gateway</h1></center>^M
</body>^M
</html>^M

Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(112): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(23): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(149): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(19150794500)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(117): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(19150794500)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(64): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(340): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"body":"<html>\r\n<head><title>502 Bad Gateway<\/title><\/head>\r\n<body>\r\n<center><h1>502 Bad Gateway<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n","response_code":502}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(112): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(23): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(149): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(19150794500)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(117): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(19150794500)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(64): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(340): Symfony\Component\Console\Application->run()
#10 {main}
```

Resolution Expectations:
- [x] Retry on 502
- [x] Implement max retry
- [x] Log when 502 happens

**Comment by dfelton** [comment]
Fixed by 115478e757a848b9335e3a6ec3e4b76846f4c9a5
