### ISSUE TITLE
Connection closed abnormally while awaiting message

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#72]
```
Shutdown Enabled at: 2021-01-15 02:49:03
Exception: Amp\Websocket\ClosedException
Code: 1006
Message: Connection closed abnormally while awaiting message; Code 1006 (ABNORMAL_CLOSE); Reason: "TCP connection closed unexpectedly"
Strace:
#0 [internal function]: Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(60): Generator->current()
#2 vendor/amphp/amp/lib/functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#3 vendor/amphp/websocket/src/Rfc6455Client.php(702): Amp\call(Object(Closure))
#4 vendor/amphp/websocket/src/Rfc6455Client.php(299): Amp\Websocket\Rfc6455Client->close(1006, 'TCP connection ...')
#5 [internal function]: Amp\Websocket\Rfc6455Client->read()
#6 vendor/amphp/amp/lib/Coroutine.php(105): Generator->send(NULL)
#7 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#8 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(NULL)
#9 vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve(NULL)
#10 vendor/amphp/amp/lib/Loop/NativeDriver.php(192): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('n', Resource id #446, NULL)
#11 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 1)
#12 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#13 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#14 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#15 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(80): Amp\Loop::run(Object(Closure))
#16 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 bin/gemini(346): Symfony\Component\Console\Application->run()
#21 {main}
```

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-19 21:31:45
Exception: Amp\Websocket\ClosedException
Code: 1008
Message: Connection closed abnormally while awaiting message; Code 1008 (POLICY_VIOLATION); Reason: "Exceeded unanswered PING limit"
Strace:
#0 [internal function]: Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(60): Generator->current()
#2 vendor/amphp/amp/lib/functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#3 vendor/amphp/websocket/src/Rfc6455Client.php(702): Amp\call(Object(Closure))
#4 vendor/amphp/websocket/src/Rfc6455Client.php(138): Amp\Websocket\Rfc6455Client->close(1008, 'Exceeded unansw...')
#5 vendor/amphp/amp/lib/Loop/NativeDriver.php(115): Amp\Websocket\Rfc6455Client::Amp\Websocket\{closure}('s', NULL)
#6 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#7 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#8 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#9 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(80): Amp\Loop::run(Object(Closure))
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(346): Symfony\Component\Console\Application->run()
#15 {main}
```

**Comment by dfelton** [comment]
I think I self-created this problem a moment ago by switching WIFI connections while the bot was running. Derp

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-22 01:10:52
Exception: Amp\Websocket\ClosedException
Code: 1006
Message: Connection closed abnormally while awaiting message; Code 1006 (ABNORMAL_CLOSE); Reason: "TCP connection closed unexpectedly"
Strace:
#0 [internal function]: Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(60): Generator->current()
#2 vendor/amphp/amp/lib/functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#3 vendor/amphp/websocket/src/Rfc6455Client.php(702): Amp\call(Object(Closure))
#4 vendor/amphp/websocket/src/Rfc6455Client.php(299): Amp\Websocket\Rfc6455Client->close(1006, 'TCP connection ...')
#5 [internal function]: Amp\Websocket\Rfc6455Client->read()
#6 vendor/amphp/amp/lib/Coroutine.php(105): Generator->send(NULL)
#7 vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#8 vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve(NULL)
#9 vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve(NULL)
#10 vendor/amphp/amp/lib/Loop/NativeDriver.php(192): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('n', Resource id #447, NULL)
#11 vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, 0.503)
#12 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#13 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#14 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#15 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(80): Amp\Loop::run(Object(Closure))
#16 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 bin/gemini(346): Symfony\Component\Console\Application->run()
#21 {main}
```

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-23 14:32:59
Exception: Amp\Websocket\ClosedException
Code: 1008
Message: Connection closed abnormally while awaiting message; Code 1008 (POLICY_VIOLATION); Reason: "Exceeded unanswered PING limit"
```

Doesn't just kill the`FillMonitor`, impacts `\Kobens\Gemini\Command\Command\Market\BookKeeper` too.

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-02-11 19:38:53
Exception: Amp\Websocket\ClosedException
Code: 1008
Message: Connection closed abnormally while awaiting message; Code 1008 (POLICY_VIOLATION); Reason: "Exceeded unanswered PING limit"
Strace:
#0 [internal function]: Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#1 vendor/amphp/amp/lib/Coroutine.php(60): Generator->current()
#2 vendor/amphp/amp/lib/functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#3 vendor/amphp/websocket/src/Rfc6455Client.php(702): Amp\call(Object(Closure))
#4 vendor/amphp/websocket/src/Rfc6455Client.php(138): Amp\Websocket\Rfc6455Client->close(1008, 'Exceeded unansw...')
#5 vendor/amphp/amp/lib/Loop/NativeDriver.php(115): Amp\Websocket\Rfc6455Client::Amp\Websocket\{closure}('s', NULL)
#6 vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#7 vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#8 vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#9 src/Command/Command/TradeRepeater/FillMonitor/WebSocket.php(80): Amp\Loop::run(Object(Closure))
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\WebSocket), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(382): Symfony\Component\Console\Application->run()
#15 {main}
```
