### ISSUE TITLE
Could not resolve host: api.gemini.com

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#79]
```
Shutdown Enabled at: 2021-01-21 22:18:42
Exception: Kobens\Core\Exception\Http\CurlException
Code: 6
Message: Could not resolve host: api.gemini.com
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.00002', '33300', 'repeater_1200_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1200_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"url":"https:\/\/api.gemini.com\/v1\/order\/new","curlinfo_connect_time":0,"curlinfo_total_time":9.991822,"curl_errno":6,"curl_error":"Could not resolve host: api.gemini.com"}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.00002', '33300', 'repeater_1200_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1200_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-22 00:49:38
Exception: Kobens\Core\Exception\Http\CurlException
Code: 6
Message: Could not resolve host: api.gemini.com
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.1', '17.22', 'repeater_262_bu...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_262_bu...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"url":"https:\/\/api.gemini.com\/v1\/order\/new","curlinfo_connect_time":0,"curlinfo_total_time":9.854118,"curl_errno":6,"curl_error":"Could not resolve host: api.gemini.com"}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.1', '17.22', 'repeater_262_bu...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_262_bu...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
No order was placed:
```
./bin/gemini order:status -c repeater_262_buy_1611276568.7152

In ResponseHandler.php line 34:
                                                                   
  Order ClientOrderId(repeater_262_buy_1611276568.7152) not found  
                                                                   

In ResponseHandler.php line 37:
                                                                                                                                                                      
  {"body":"{\"result\":\"error\",\"reason\":\"OrderNotFound\",\"message\":\"Order ClientOrderId(repeater_262_buy_1611276568.7152) not found\"}","response_code":404}  
```
```

**Comment by dfelton-chwy** [comment]
```
Shutdown Enabled at: 2021-01-23 06:04:30
Exception: Kobens\Core\Exception\Http\CurlException
Code: 6
Message: Could not resolve host: api.gemini.com
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.15', '22.47', 'repeater_1083_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1083_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"url":"https:\/\/api.gemini.com\/v1\/order\/new","curlinfo_connect_time":0,"curlinfo_total_time":9.840405,"curl_errno":6,"curl_error":"Could not resolve host: api.gemini.com"}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.15', '22.47', 'repeater_1083_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1083_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by dfelton** [comment]
```
Shutdown Enabled at: 2021-01-23 06:04:30
Exception: Kobens\Core\Exception\Http\CurlException
Code: 6
Message: Could not resolve host: api.gemini.com
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.15', '22.47', 'repeater_1083_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1083_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"url":"https:\/\/api.gemini.com\/v1\/order\/new","curlinfo_connect_time":0,"curlinfo_total_time":9.840405,"curl_errno":6,"curl_error":"Could not resolve host: api.gemini.com"}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(99): Kobens\Core\Http\Curl->request('https://api.gem...', Array)
#1 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(62): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/new', Array)
#2 src/Command/Command/TradeRepeater/Buyer.php(132): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'buy', '0.15', '22.47', 'repeater_1083_b...')
#3 src/Command/Command/TradeRepeater/Buyer.php(101): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Model\Trade), 'repeater_1083_b...')
#4 src/Command/Command/TradeRepeater/Buyer.php(75): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Buyer->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Buyer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 bin/gemini(346): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by dfelton** [comment]
Had this issue happen again immediately after the last occurrence. This time, the HTTP Message for the order _did_ get received by the exchange. The only reason it wasn't placed was a `MakerOrCancelWouldTake`. Thus, manual resolution was easy, but this proves the HTTP message can be received, and order status needs to be checked.
