### ISSUE TITLE
Warning: bcdiv(): Division by zero 

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#80]
Happened when it was lacking any orders on the given pair.

```
Warning: bcdiv(): Division by zero in vendor/kobens/kobens-math/src/BasicCalculator/Divide.php on line 18
Code: 0
Class: TypeError
Message: Return value of Kobens\Math\BasicCalculator\Divide::getResult() must be of the type string, null returned
Trace:
#0 src/TradeRepeater/Watcher/TradeSpread.php(107): Kobens\Math\BasicCalculator\Divide::getResult('0', '0', 2)
#1 src/Command/Command/TradeRepeater/Watcher.php(190): Kobens\Gemini\TradeRepeater\Watcher\TradeSpread::getTable(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Kobens\Gemini\TradeRepeater\Watcher\Helper\Data), 'batusd')
#2 src/Command/Command/TradeRepeater/Watcher.php(154): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->getData(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), false, false, false, false)
#3 src/Command/Command/TradeRepeater/Watcher.php(94): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->main(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), false, false, false, false)
#4 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Watcher->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Watcher), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 bin/gemini(346): Symfony\Component\Console\Application->run()
```

**Comment by dfelton** [comment]
The `Kobens\Command\Command\TradeRepeater\Watcher` command has been deprecated and since removed. This is basically a duplicate of #90 (although this reported first, that one replaces this as it has the new command which replaced `Watcher`).
