### ISSUE TITLE
Nonce has not increased since your last call to the Gemini API.

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-gemini#81]
```
Shutdown Enabled at: 2021-01-18 05:14:37
Exception: Kobens\Gemini\Exception
Code: 400
Message: Nonce '???' has not increased since your last call to the Gemini API.
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(118): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(48): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(35): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getResponse(Array)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(196): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(20130469758)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(160): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(20130469758)
#5 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(117): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->iterateSellOrders(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Kobens\Gemini\Exchange\Currency\Pair))
#6 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(81): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, Object(Kobens\Gemini\Exchange\Currency\Pair))
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(346): Symfony\Component\Console\Application->run()
#12 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"body":"{\"result\":\"error\",\"reason\":\"InvalidNonce\",\"message\":\"Nonce '???' has not increased since your last call to the Gemini API.\"}","response_code":400}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(118): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(48): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(35): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getResponse(Array)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(196): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(20130469758)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(160): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(20130469758)
#5 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(117): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->iterateSellOrders(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Kobens\Gemini\Exchange\Currency\Pair))
#6 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(81): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, Object(Kobens\Gemini\Exchange\Currency\Pair))
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(346): Symfony\Component\Console\Application->run()
#12 {main}
```

**Comment by dfelton** [comment]
Shutdown Enabled at: 2021-01-25 00:01:20
Exception: Kobens\Gemini\Exception\Api\Reason\InvalidNonceException
Code: 400
Message: Nonce '161153287963707200' has not increased since your last call to the Gemini API.
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(118): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(49): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(36): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getResponse(Array)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(226): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(20515392144)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(190): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(20515392144)
#5 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(146): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->iterateSellOrders(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, NULL)
#6 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(96): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, NULL)
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(345): Symfony\Component\Console\Application->run()
#12 {main}

Previous Exception:
Exception: Exception
Code: 0
Message: {"body":"{\"result\":\"error\",\"reason\":\"InvalidNonce\",\"message\":\"Nonce '161153287963707200' has not increased since your last call to the Gemini API.\"}","response_code":400}
Strace:
#0 src/Api/Rest/PrivateEndpoints/Request.php(118): Kobens\Gemini\Api\Helper\ResponseHandler->handleResponse(Object(Kobens\Core\Http\Response))
#1 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(49): Kobens\Gemini\Api\Rest\PrivateEndpoints\Request->getResponse('/v1/order/statu...', Array, Array, true)
#2 src/Api/Rest/PrivateEndpoints/OrderStatus/OrderStatus.php(36): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getResponse(Array)
#3 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(226): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderStatus\OrderStatus->getStatus(20515392144)
#4 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(190): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->isFilled(20515392144)
#5 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(146): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->iterateSellOrders(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, NULL)
#6 src/Command/Command/TradeRepeater/FillMonitor/Rest.php(96): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->mainLoop(Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, NULL)
#7 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\FillMonitor\Rest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/gemini(345): Symfony\Component\Console\Application->run()
#12 {main}
